spring.application.name=firstapi
spring.profiles.default=dev

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postsdb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

app.auth.jwt-secret=${JWT_SECRET}
app.auth.access-tt1=15m
app.auth.refresh-tt1=7d